[project]
name = "flasklearning"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-scss>=0.5",
    "jinja2>=3.1.6",
    "pydantic>=2.11.7",
    "pymongo>=4.14.1",
]
